# Tap
tap "homebrew/bundle"
tap "supabase/tap"

# Formulae
brew "curl"
brew "duktape"
brew "ffmpeg"
brew "fzf"
brew "gcc"
brew "genact"
brew "gh"
brew "git"
brew "imagemagick"
brew "lazydocker"
brew "lazygit"
brew "lefthook"
brew "lua"
brew "mpv"
brew "neofetch"
brew "neovim"
brew "node"
brew "npm"
brew "nvm"
brew "pnpm"
brew "posting"
brew "powerlevel10k"
brew "pyenv"
brew "ripgrep"
# brew "sqlite"
brew "supabase/tap/supabase"
brew "tmux"
# brew "tpm"
brew "tree"
# brew "tree-sitter"
brew "uv"
# brew "vim"
brew "yazi"
# brew "yt-dlp"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# Casks
# cask "aquaskk"
cask "arc"
cask "deepl"
cask "docker"
cask "font-jetbrains-mono-nerd-font"
cask "ghostty"
cask "hammerspoon"
cask "notion"
cask "obsidian"
cask "postman"
cask "raycast"
cask "slack"
cask "visual-studio-code"
# cask "wezterm"
